require("BasicSettings.settings-")
require("BasicSettings.keys-")
require("PackerConfig.packer-config")
require("LspConfig.lspconfig")
require("LspConfig.lspsaga")
require("LspConfig.mason")
require("LspConfig.null-ls")

require("CmpConfig.nvim-cmp")
require("Pep8.pepa8")
require("TreeSitterConfig.treesitter")
require("Colorscheme.colorscheme-")
require("ToggleTerminal.toggleterminal-")
require("Bar-Bar.barbar__plug")
require("ChrisForTmux.chrisForTmux-")
require("NvimTree.nvim_tree_config")
require("Lualine.lualine-")
